apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: rockyapps
  annotations:
    nginx.org/ssl-services: {{ .Values.app }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.hosts }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.app }}
            port:
              number: {{ .Values.port }}
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.hosts }}
    secretName: {{ .Values.secretName }}
status:
  loadBalancer: {}
