apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app }}
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.app }}
spec:
  ports:
  - port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.targetPort }}
  selector:
    app: {{ .Values.app }}
  type: {{ .Values.type }}
status:
  loadBalancer: {}
